# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=1.0.2
maven_group=net.vg
archives_name=structurevoidable-26-1-2
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=26.1.2
# Dependencies
architectury_api_version=20.0.7
fabric_loader_version=0.19.3
fabric_api_version=0.153.0+26.1.2
neoforge_version=26.1.2.76

# ModMenu version (for Fabric only)
modmenu_version = 18.0.0-beta.1
